server:
  port: 8888
spring:
  application:
    name: spring-cloud-config-server-estudo
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aplaraujo/spring-config-server-estudo
          search-paths: 'greeting-service'
#  profiles:
#    active:
#      - native